Fix NoClassDefFoundError in PfiStructureTest
* Align io.ktor versions between Web5 and tbDEX manually
* Remove unused imports from PfiStructureTest
* Add dependency on ktor-server-content-negotiation-jvm, necesary to run TbdexHttpServer