PFI Structure Tests (#1290)
* Add tests for PFI Structure doc

* Remove unneeded text with deleted snippets

* Fix NoClassDefFoundError in PfiStructureTest

* Align io.ktor versions between Web5 and tbDEX manually
* Remove unused imports from PfiStructureTest
* Add dependency on ktor-server-content-negotiation-jvm, necesary to run TbdexHttpServer

* Put some comments as suggested TODOs for Chris

* Try to add tests

* Fix test by modifying did initialization for authorization

* Apply suggestions from code review

Co-authored-by: Jiyoon Koo <jiyoon@tbd.email>

* Fix build error

* adding missing assertions

* Update site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt

* simplifying status code assertion

* adding TODO for Kotlin tests

---------

Co-authored-by: Andrew Lee Rubinger <alr@alrubinger.com>
Co-authored-by: Angie Jones <jones.angie@gmail.com>
Co-authored-by: Jiyoon Koo <jiyoon@tbd.email>